# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0008_auto_20161007_1907'),
        ('post', '0011_auto_20161122_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_work', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=1000)),
                ('dest_lat', models.CharField(max_length=1000)),
                ('dest_long', models.CharField(max_length=1000)),
                ('source_lat', models.CharField(max_length=100)),
                ('source_long', models.CharField(max_length=1000)),
                ('source_address', models.CharField(max_length=1000)),
                ('dest_address', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=50)),
                ('payment', models.BooleanField()),
                ('budget_min', models.CharField(max_length=5)),
                ('budget_max', models.CharField(max_length=5)),
                ('details', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='image/no-image.jpg', upload_to='image/')),
                ('v_admin', models.BooleanField()),
                ('near_by', models.CharField(default='0.0', max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
            ],
        ),
    ]
