# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20161123_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='v_admin',
            field=models.BooleanField(default=True),
        ),
    ]
