# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-26 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161126_1911'),
        ('post', '0016_auto_20161123_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_response',
            name='res_id',
        ),
        migrations.AddField(
            model_name='post_response',
            name='budget_max',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='post_response',
            name='budget_min',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='post_response',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='budget_max',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='budget_min',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
