# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20161201_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_response',
            name='status',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AlterField(
            model_name='post_response',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
