# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=1000)),
                ('budget', models.IntegerField()),
                ('loc', models.CharField(max_length=100)),
                ('s_time', models.DateTimeField(max_length=50)),
                ('e_time', models.DateTimeField(max_length=50)),
                ('about', models.CharField(max_length=500)),
                ('v_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='post_response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=26)),
                ('mobile_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('cur_loc', models.FloatField()),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('dob', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
