# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160925_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='pramud', max_length=50),
        ),
    ]
