# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20161123_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
