# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20161126_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits',
            field=models.CharField(default='50', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_id',
            field=models.CharField(default='Null', max_length=2000),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
